//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrite.Framework.Builders.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuildErrorSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuildErrorSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Democrite.Framework.Builders.Resources.BuildErrorSR", typeof(BuildErrorSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula only allowed aphabetical, logical symboles (&amp;, |, ^) and parenthesis are allowed..
        /// </summary>
        internal static string FormulaOnlyCharAllowed {
            get {
                return ResourceManager.GetString("FormulaOnlyCharAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] - {1}.
        /// </summary>
        internal static string InvalidParameterExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidParameterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory value null or missing.
        /// </summary>
        internal static string MandatoryValueMissing {
            get {
                return ResourceManager.GetString("MandatoryValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable(s) &apos;{0}&apos; are missing from logical fomula..
        /// </summary>
        internal static string VariableNameIsMissingFromFormula {
            get {
                return ResourceManager.GetString("VariableNameIsMissingFromFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable names information are miss aligned with listener setups. All listen sources must have a variables names an be used in  formula..
        /// </summary>
        internal static string VariableNamesIsNotAlignWIthSources {
            get {
                return ResourceManager.GetString("VariableNamesIsNotAlignWIthSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable must only be composed of aphabetical values upper and lower..
        /// </summary>
        internal static string VariableOnlyCharAllowed {
            get {
                return ResourceManager.GetString("VariableOnlyCharAllowed", resourceCulture);
            }
        }
    }
}
