# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - main
      - dev

resources:
  repositories:
    - repository: Yaml-Templates
      type: git
      name: Yaml-Templates
#      ref: refs/heads/dev

parameters:
  - name: debug_display
    displayName: Define debug information are requested
    type: boolean
    default: false

jobs:
  - job: Window
    pool:
      vmImage: 'windows-latest'

    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 8.x
          includePreviewVersions: true # Required for preview versions

      - template: /Templates/dotnet/full-build-test-export-steps.yaml@Yaml-Templates
        parameters: 
          debug_display: ${{ parameters.debug_display }}
          solution_file_name: $(solution-name)
          exclude_from_coverage_regex: '(((Orleans.)|(h.)|(coverlet.))[a-zA-Z.]+.dll)|(Democrite.[a-zA-Z.]+.unittests.dll)'

#   - job: Linux
#     pool:
#       vmImage: 'ubuntu-latest'
      
#     steps:
#       - task: UseDotNet@2
#         displayName: 'Install .NET Core SDK'
#         inputs:
#           version: 8.x
#           includePreviewVersions: true # Required for preview versions

#       - template: /Templates/dotnet/full-build-test-export-steps.yaml@Yaml-Templates
#         parameters: 
#           debug_display: ${{ parameters.debug_display }}
#           solution_file_name: $(solution-name)
#           exclude_from_coverage_regex: '(((Orleans.)|(h.)|(coverlet.))[a-zA-Z.]+.dll)|(Democrite.[a-zA-Z.]+.unittests.dll)'
