//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Democrite.Framework.Node.Abstractions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NodeAbstractionExceptionSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NodeAbstractionExceptionSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Democrite.Framework.Node.Abstractions.Resources.NodeAbstractionExceptionSR", typeof(NodeAbstractionExceptionSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VGrain implementation of id &quot;{0}&quot; doesn&apos;t have been founded..
        /// </summary>
        internal static string VGrainIdNotFounded {
            get {
                return ResourceManager.GetString("VGrainIdNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VGrain implementation of type &quot;{0}&quot; doesn&apos;t have been founded..
        /// </summary>
        internal static string VGrainTypeNotFounded {
            get {
                return ResourceManager.GetString("VGrainTypeNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not found artificat Id({0}) type &apos;{1}&apos;..
        /// </summary>
        internal static string ArtifactMissing {
            get {
                return ResourceManager.GetString("ArtifactMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact preparation failed - Type : {0}.
        /// </summary>
        internal static string ArtifactPreparationFailed {
            get {
                return ResourceManager.GetString("ArtifactPreparationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artificat Id({0}) is of type &apos;{1}&apos; but expect type &apos;{2}&apos;..
        /// </summary>
        internal static string ArtifactWrongType {
            get {
                return ResourceManager.GetString("ArtifactWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method with signature &quot;{0}&quot; doesn&apos;t have been founded on type &quot;{1}&quot;..
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence definition id &apos;{0}&apos; is missing from the ISequenceDefinitionManager or parent definition.
        /// </summary>
        internal static string SequenceDefinitionMissing {
            get {
                return ResourceManager.GetString("SequenceDefinitionMissing", resourceCulture);
            }
        }
    }
}
